[package]
name = "iota-spammer"
version = "0.0.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>"]
description = "A iota transaction spammer"
license = "MIT"
readme = "README.md"
keywords = ["iota"]
repository = "https://github.com/njaremko/iota-spammer"

[dependencies]
clap = "2.32"
failure = "0.1"
iota-lib-rs = "0.0.26"
num_cpus = "1.8"
term_size = "0.3"